#!/bin/sh

exit_if_fails () {
	if [ $? -ne 0 ]; then
		pop_stashed_files
		exit 1
	fi
}

pop_stashed_files () {
	if [ -n "$hasChanges" ]; then
		(( step++ ))
		echo "\033[0;34m$step. Applying stashed changes...\033[0m"
		git stash pop -q
	fi
}

post_test_process () {
	testStatus=$?
	coverageChanged=$(git diff)
	if [ $testStatus -eq 0 ]; then
		if [ "$coverageChanged" ]; then
			git add coverage/lcov.info
		fi
	else
		if [ "$coverageChanged" ]; then
			git checkout -- coverage/lcov.info
		fi
		pop_stashed_files
		exit 1
	fi
}

step=1
hasChanges=$(git diff)
if [ -n "$hasChanges" ]; then
	echo "\033[0;34m0. Stashing unstaged changes...\033[0m"
	git stash push --keep-index
fi
echo "\033[0;34m$step. Analyzing...\033[0m"
flutter analyze
exit_if_fails
(( step++ ))
echo "\033[0;34m$step. Testing...\033[0m"
flutter test --coverage
post_test_process
(( step++ ))
echo "\033[0;34m$step. Validating formatting...\033[0m"
dart format --set-exit-if-changed lib test
pop_stashed_files
echo "\033[0;34m$step. Push...\033[0m"