name: Pull Request Checker

on: 
  pull_request: [ { name: '**' } ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run Flutter Validations
        run: |
          flutter packages get
          flutter analyze
          flutter test
          dart format --set-exit-if-changed lib test